server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eliza_db
    username: postgres
    password: your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  websocket:
    stomp:
      websocket:
        enabled: true
    stomp-endpoint: /ws
    stomp-broker-relay:
      prefix: /topic
      relay-host: localhost
      relay-port: 61613
      client-login: guest
      client-passcode: guest

jwt:
  secret: your-secret-key
  expiration: 86400000
  header: Authorization
  prefix: Bearer

firebase:
  credentials: src/main/resources/service-account.json
  database-url: https://your-project.firebaseio.com
